import calculation_test_price_wo_vat_for_13_per
import calculation_test_price_wo_vat_for_23_per
import calculation_test_price_wo_vat_for_6_per
import calculation_test_price_vat_field_for_23_per
import calculation_test_price_incl_vat_field_for_23_per

calculation_test_price_wo_vat_for_23_per.launch_test()
calculation_test_price_wo_vat_for_13_per.launch_test()
calculation_test_price_wo_vat_for_6_per.launch_test()
calculation_test_price_vat_field_for_23_per.launch_test()
calculation_test_price_incl_vat_field_for_23_per.launch_test()